<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework Condition="'$(TargetFramework)' == ''">net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup>
  <Import Project="../../Version.props" />
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../src/Dockyard.Blazor.csproj" Condition="'$(UsePackage)' != 'true'" />
    <PackageReference Include="Dockyard.Blazor" Version="$(Version)" Condition="'$(UsePackage)' == 'true'" />
  </ItemGroup>
</Project>
